#
# COPYRIGHT Ericsson 2023-2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-esoa-key-management-agent.serviceAccountName" . }}
  labels:
  {{- include "eric-esoa-so-library-chart.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-esoa-so-library-chart.annotations" . | nindent 4 }}
{{- end }}
---

# Explicitly created secret, referencing above service account, which can be mounted by name
# and whose JWT token will not expire
#
# Long-term stability is required as it will be referred to when setting up KMS access and the
# JWT token will be used when logging in to KMS
#
# Will be populated with the service account token.

{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eric-esoa-key-management-agent.serviceAccountSecretName" . }}
  annotations:
  {{- include "eric-esoa-so-library-chart.annotations" . | nindent 4 }}
    "kubernetes.io/service-account.name": {{ template "eric-esoa-key-management-agent.serviceAccountName" . }}
  labels:
  {{- include "eric-esoa-so-library-chart.labels" . | nindent 4 }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/service-account-token
{{- end }}
