#
# COPYRIGHT Ericsson 2023-2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-esoa-key-management-agent.fullname" . }}
  labels:
  {{- include "eric-esoa-so-library-chart.labels" . | nindent 4 }}
  {{- include "eric-esoa-so-library-chart.bamPartofLabel" .| nindent 4 }}
  annotations:
  {{- include "eric-esoa-so-library-chart.annotations" . | nindent 4 }}
  {{- include "eric-esoa-so-library-chart.bamDiscoveryAnnotation" .| nindent 4 }}
spec:
  type: {{ .Values.service.type | quote }}
  {{- if .Values.global }}
  {{- if .Values.global.internalIPFamily }}
  ipFamilies: [{{ .Values.global.internalIPFamily }}]
  {{- end }}
  {{- end }}
  ports:
    {{- if eq (include "eric-esoa-so-library-chart.global-security-tls-enabled" .) "true" }}
    - name: https
      port: {{ .Values.service.port.https }}
      targetPort: {{ .Values.port.https }}
    {{- else }}
    - name: http
      port: {{ .Values.service.port.http }}
      targetPort: {{ .Values.port.http }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "eric-esoa-so-library-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
